# x = 5

# # Делаем утверждение: "переменная x равна пяти"
# # Синтаксис: assert <утверждение>, 'Cообщение об ошибке'
# assert x == 5, 'Сообщение, которое вернётся, если утверждение не истинно'
# # Утверждение вернёт True, так что сообщение не будет показано

# assert x == 4, 'Сообщение, которое вернётся, если утверждение не истинно'
# # Утверждение x == 4 вернёт False, и в этом случае в консоль будет выведено
# # ...
# # AssertionError: Сообщение, которое вернётся, если утверждение не истинно

# x = [0, 1, 2, 3, 4]
# assert len(x) == 5, f'Хьюстон, у нас проблемы: значение len(x) равно {len(x)}!'
# x.append(5)
# assert len(x) == 5, f'Хьюстон, у нас проблемы: значение len(x) равно {len(x)}!'

# assert 2 + 2 == 5
